sims/nic/i40e_bm: PTP support (PHC, rx/tx timestamping)
simbricks/simbricks pull request #125
Opened 2024-06-24 12:30 UTC by q713

Adds support for hardware timestamping to the nic behavioral model. The actual changes are cherry-picked from the splitsim branch.

2024-06-25 14:02 UTC, FreakyPenguin requested changes
Can you squash this commit into the previous one?

Otherwise it looks good.

2024-06-26 12:38 UTC, marvin71 approved these changes
I think this looks good :slightly_smiling_face:

2024-06-26 12:43 UTC, marvin71 approved these changes

2024-06-26 13:20 UTC, FreakyPenguin approved these changes
Looks good to me now! Thanks!

2024-06-26 13:20 UTC, merged