BMV2 Integration
simbricks/simbricks pull request #127
Opened 2024-07-08 15:22 UTC by JLin-Li

Adding SimBricks integration for P4 reference behavior model BMV2. Functionality verified using qemu_udp_single experiment.

To-dos:
  - Add synchronization support
  - Add p4c support to generate simple switch from p4 source code

2024-07-09 13:02 UTC, marvin71 reviewed
In general this looks good to me, but I haven't tested it. I have only one minor comment regarding the clean target.

2024-07-10 15:03 UTC, jonas-kaufmann requested changes
Nice, thanks for the PR! Overall looks good to me. Can you squash the commits though using `git rebase`?  If possible we want to have a clean history. Concretely, I'd propose to have one commit that adds the submodule, everything necessary to build bmv2 and the integration in `simulators.py`. In a second commit you could then modify the experiment.

2024-07-11 13:52 UTC, JLin-Li commented on sims/external/rules.mk
>  EXTERNAL_CLEAN_TASKS := gem5-clean qemu-clean ns-3-clean femu-clean
Thanks!

2024-07-11 13:52 UTC, JLin-Li commented on sims/external/rules.mk
> +	make -j
Sounds good!

2024-07-11 13:52 UTC, JLin-Li commented on docker/Dockerfile.buildenv
> + ENV LD_LIBRARY_PATH=/usr/local/lib
Resolved!

2024-07-11 20:07 UTC, jonas-kaufmann approved these changes

2024-07-12 07:21 UTC, merged