applies pre-commit hooks to whole repo and fixes all pylint issues
simbricks/simbricks pull request #21
Opened 2022-07-02 20:11 UTC by Kaufi-Jonas

Based on #18. Merge #18 first for a clean commit history. I have disabled warnings for missing class and module doc strings for now and added pytype and pylint to the` lint` and `lint-all` Makefile targets again.

Here are some notes on what to look out for to avoid common pylint issues I encountered:
- always use f-strings to include a variable's value in a string
- use `(...)` instead of `\` to split up a statement over multiple lines (dictated by Google's style guide)
- make use of the `with` statements for resource operations, e.g. opening a file for reading
- always specify the encoding to be used when opening a file via `open()`; `open()` defaults to the locale encoding, which is not necessarily UTF-8 (https://peps.python.org/pep-0597/)
- don't use wildcard imports `from namespace.module import *`
- it's okay to disable pylint warnings where it makes sense, can be done at line or block level via  a comment, e.g., `# pylint: disable=redefined-outer-name`

2022-07-08 12:58 UTC, FreakyPenguin reviewed
Erm das sieht mir gerade etwas übereifrig aus so... Könnten wir eventuell erstmal nur den python code umformatieren? Das scheint ja so ziemlich wahllos dateien umzuformatieren und ich vermute da könnte einiges kaputt gehen. (siehe weiter Kommentare).

2022-07-08 13:10 UTC, FreakyPenguin requested changes
Siehe die paar Kommentare, ich glaube da sollten wir erstmal etwas weniger aggresiv umformatieren. Also nur den python code (ohne graphlib) und auch sicherstellen dass die jsons nicht verändert werden.

2022-07-08 13:10 UTC, FreakyPenguin commented on experiments/pyexps/ScaleHost.py
> +import simbricks.experiments as exp
Was hat es denn hiermit auf sich?

2022-07-08 13:10 UTC, FreakyPenguin commented on experiments/simbricks/utils/graphlib.py
>  # From cpython repo (introduced upstream in python 3.9)
Graphlib sollten wir vielleicht vom ganzen Linting ausschliessen. Das ist ja direkt aus dem python repo kopiert da das zumindest eine Zeit lang noch nicht in unserer verwendeten python version drin war. Da würde ich gerne die originale Formatierung beibehalten.

2022-07-08 13:10 UTC, FreakyPenguin commented on results/paper_data/ScaleHost/gt-ib-sw-Host-1000m-1-1.json
> -{"exp_name": "gt-ib-sw-Host-1000m-1", "metadata": {}, "start_time": 1620084117.1460905, "end_time": 1620092399.7460394, "sims": {"nic.server.0.": {"class": "I40eNIC", "cmd": ["/DS/endhost-networking/
Die jsons sollten wir auch so beibehalten wie sie als output rauskommen.

2022-07-08 13:10 UTC, FreakyPenguin commented on experiments/simbricks/utils/graphlib.py
>          self.npredecessors = 0
Auch hier die vielleicht einfach als excluded setzen fürs linten...

2022-07-10 11:41 UTC, Kaufi-Jonas commented on experiments/pyexps/ScaleHost.py
> +import simbricks.experiments as exp
isort hat Teile vom `simbricks` namespace als first- und andere als third-party erkannt. Ist mit https://github.com/simbricks/simbricks/pull/21/commits/27a887140cedebf9de1dfdf582b134b671dd0625 gefixed.

2022-07-10 11:46 UTC, Kaufi-Jonas commented
> Erm das sieht mir gerade etwas übereifrig aus so... Könnten wir eventuell erstmal nur den python code umformatieren? Das scheint ja so ziemlich wahllos dateien umzuformatieren und ich vermute da könnte einiges kaputt gehen. (siehe weitere Kommentare).

pre-commit now only reformats Python files. I excluded `graphlib.py` via the Makefile targets for `yapf` and `isort` and pre-commit now these instead of using separate hooks. This means that we don't have to adjust parameters for `yapf` and `isort` in two places when there are adjustments to be made in the future.

2022-07-12 13:37 UTC, merged